### ISSUE TITLE
Getting error from React.createElement since graphiql v0.17.3

### ISSUE THREAD

**Issue by chetabahana** [graphql/graphiql#1090]
#### Case

I updated [package](https://github.com/chetabahana/tree/blob/latest/test/fixtures/three.graphql/package.json#L31) deps from v0.16.0 to v0.17.0, v0.17.1 and v0.17.2 which all are _[fine](https://chetabahana.github.io/tree/test/fixtures/three.graphql/index.html)_.
But got errors from the version v0.17.3 up to the latest v0.17.5 on [React.createElement](https://github.com/chetabahana/tree/blob/0c2022ed326ed7480cedf57030d41015579a23f1/test/fixtures/three.graphql/editor.js#L96):

```
  const reactElement = React.createElement(GraphiQL, {
    query: currentQuerySource || kDefaultQuery,
    fetcher: fetcher,
    variables: '',
    response: '',
    onEditQuery: onEditQuery,
    onEditVariables: onEditVariables,
  })

```
Kindly please advise. Thanks.

#### Details
```js
build.js:84381 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
warningWithoutStack @ build.js:84381
build.js:82442 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at createFiberFromTypeAndProps (build.js:82442)
    at createFiberFromElement (build.js:82465)
    at reconcileSingleElement (build.js:71339)
    at reconcileChildFibers (build.js:71399)
    at reconcileChildren (build.js:73909)
    at updateHostRoot (build.js:74380)
    at beginWork$1 (build.js:76003)
    at HTMLUnknownElement.callCallback (build.js:56149)
    at Object.invokeGuardedCallbackDev (build.js:56198)
    at invokeGuardedCallback (build.js:56253)
build.js:80104 Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (build.js:56209)
    at invokeGuardedCallback (build.js:56253)
    at beginWork$$1 (build.js:81593)
    at performUnitOfWork (build.js:80511)
    at workLoopSync (build.js:80484)
    at performSyncWorkOnRoot (build.js:80083)
    at scheduleUpdateOnFiber (build.js:79511)
    at updateContainer (build.js:82916)
    at build.js:83341
    at unbatchedUpdates (build.js:80246)
```

#### Screenshot
![screnschot](https://user-images.githubusercontent.com/36441664/70664348-d27b6700-1c9c-11ea-9f49-63ff4656e513.png)

**Comment by acao** [comment]
hmm! so how are you importing graphiql, from CDN or via webpack using `import` or what?
from what I'm seeing, it seems like you might be doing a commonjs import, which means you need to 
```js
// index.js
const { default: GraphiQL } = require('graphiql'):
```
now, because before we had this:
```js
// index.js
module.exports = GraphiQL
```
but that broke tree shaking

**Comment by acao** [comment]
so my bad, I should have updated docs and possibly made this a breaking change

**Comment by acao** [comment]
let me know if that fix works for you. here are the available import patterns:

```js
import { GraphiQL } from 'graphiql';
import GraphiQL from 'graphiql';
// note: using cjs will ead to larger bundler builds
const { GraphiQL } = require('graphiql');
const { default: GraphiQL } = require('graphiql');
const GraphiQL = require('graphiql').default;
```

**Comment by chetabahana** [comment]
I was using this code :
```
const GraphiQL = require('graphiql')
```

I will try to use your suggestion and let you know.

**Comment by chetabahana** [comment]
Thank you @acao. There is one working which is:
```js
const { default: GraphiQL } = require('graphiql');
```

These two are not working (same errors):
```js
const { GraphiQL } = require('graphiql');
const GraphiQL = require('graphiql').default;
```
Also the for [Import code](https://github.com/chetabahana/tree/commit/053ed27176b322d5317b51dc8bffc14479984ae2#diff-c4de6f48201fa7a8aa30cd0516a80618R4):
```js
import { GraphiQL } from 'graphiql';
import GraphiQL from 'graphiql';
```

Detail [error for the import](https://github.com/chetabahana/tree/commit/053ed27176b322d5317b51dc8bffc14479984ae2/checks?check_suite_id=354224547#step:4:686):
```js
Error: Parsing file /home/runner/work/tree/tree/test/fixtures/three.graphql/editor.js: 'import' and 'export' may appear only with 'sourceType: module' (4:0)
    at Deps.parseDeps (/home/runner/work/tree/tree/test/fixtures/three.graphql/node_modules/module-deps/index.js:510:15)
    at getDeps (/home/runner/work/tree/tree/test/fixtures/three.graphql/node_modules/module-deps/index.js:438:44)
    at /home/runner/work/tree/tree/test/fixtures/three.graphql/node_modules/module-deps/index.js:421:38
    at ConcatStream.<anonymous> (/home/runner/work/tree/tree/test/fixtures/three.graphql/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:215:7)
    at finishMaybe (/home/runner/work/tree/tree/test/fixtures/three.graphql/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/home/runner/work/tree/tree/test/fixtures/three.graphql/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/home/runner/work/tree/tree/test/fixtures/three.graphql/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/home/runner/work/tree/tree/test/fixtures/three.graphql/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:299:28)
```

**Comment by acao** [comment]
interesting! import/export issue looks like its related to your bundler perhaps. i should add some tests for this as well. what are you using to bundle GraphiQL?

**Comment by chetabahana** [comment]
Here is the code:
```
browserify editor.js -t brfs -o build.js --no-babelrc
```

It is placed in a [build script](https://github.com/chetabahana/tree/blob/latest/test/fixtures/three.graphql/scripts/build.sh#L4) and run with [npm run-script](https://github.com/chetabahana/tree/commit/053ed27176b322d5317b51dc8bffc14479984ae2/checks?check_suite_id=354224547#step:4:559) via [package.json](https://github.com/chetabahana/tree/blob/bbb2cc558c3ff9a168bdff611f867cd8f82cde71/test/fixtures/three.graphql/package.json#L40)
 think it is related to Babel. The newer version requires you install whichever plugins needs.
I am referring to this answer in Stackoverflow: https://stackoverflow.com/a/40029232/4058484

**Comment by acao** [comment]
ah ok! we just migrated our library build from the original browserify setup, but yeah it should still be supported for consumption just fine! 

the babel config and plugin versions in the webpack example should give you a good start if you still need to finesse them!

**Comment by chetabahana** [comment]
Ok thanks. I am going to look in to that option.

**Comment by acao** [comment]
i think you'll need to use `babelify` etc as well

**Comment by chetabahana** [comment]
i am learning on it, the `babelify` is already in my current [package.json](https://github.com/chetabahana/tree/blob/bbb2cc558c3ff9a168bdff611f867cd8f82cde71/test/fixtures/three.graphql/package.json#L27) but still confuse how to set webpack in to it, also for the [build code:](https://github.com/chetabahana/tree/blob/latest/test/fixtures/three.graphql/scripts/build.sh#L4)
```js
browserify editor.js -t brfs -o build.js --no-babelrc
```
i do appreciate if you could advise more, here is my tutorial link at the moment
https://medium.com/@kishan020696/react-16-with-webpack-4-and-babel-7-7befed102817

**Comment by chetabahana** [comment]
Finally I get my package [up and running](https://chetabahana.github.io/tree/test/fixtures/three.graphql/index.html) using your [import code](https://github.com/chetabahana/tree/blob/f16510e9024e1ef7c94743c454255dd0785fc479/test/fixtures/three.graphql/editor.js#L8):

```
import GraphiQL from 'graphiql';
```
By following documentation of _[Babelify Options](https://github.com/babel/babelify#options)_ and _[Browserify Handbook on Configuring Transforms](https://github.com/browserify/browserify-handbook#configuring-transforms)_ I changed the [bundel code](https://github.com/chetabahana/tree/blob/f16510e9024e1ef7c94743c454255dd0785fc479/test/fixtures/three.graphql/scripts/build.sh#L7) as below:

```
browserify -t brfs \
-t [ babelify --presets [ @babel/preset-env @babel/preset-react ] ] \
editor.js > build.js --no-babelrc
```

Here is my current [package.json](https://github.com/chetabahana/tree/blob/f16510e9024e1ef7c94743c454255dd0785fc479/test/fixtures/three.graphql/package.json#L25).   I am still on the way to bundle with webpack.

**Comment by dimaMachina** [comment]
no longer relevant since we dropped cjs build and default exports in graphiql 4
