### ISSUE TITLE
[tsconfig]: target is set to esnext

### ISSUE THREAD

**Issue by pranshuchittora** [graphql/graphiql#1407]
```
  process.stderr.write((error?.stack ?? String(error)) + '\n');
                                    ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/undefined/OSS/graphql/graphiql/packages/graphql-language-service/dist/cli.js:7:34)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

### Solution 
set target to `es6` fixes the issue

What's your opinion @acao ??

**Comment by acao** [comment]
we have a discussion going about this for months already, and aren't sure yet what is the best option. for now, developers will need to transpile the node modules using webpack/rollup/etc, as targeting `es6` leads to very under-performant execution for async/await in the LSP

**Comment by acao** [comment]
here's a live demo of it transpiled for browsers:

https://graphiql-test.netlify.com/webpack/

the configuration to produce the above example:
https://github.com/graphql/graphiql/tree/master/examples/graphiql-webpack

**Comment by pranshuchittora** [comment]
In that case, we must provide this information in the docs.
That before shipping do transpile it according to the execution environment.

**Comment by acao** [comment]
we set `main` cjs target to `es6` for the last few minor versions of `graphiql`, fyi!
