### ISSUE TITLE
Error when trying to run example

### ISSUE THREAD

**Issue by scottschulthess** [graphql/graphiql#149]
```ReferenceError: Promise is not defined<br> &nbsp; &nbsp;at /Users/sschulthess/other_code/graphiql/example/node_modules/express-graphql/dist/index.js:76:9<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/sschulthess/other_code/graphiql/example/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/Users/sschulthess/other_code/graphiql/example/node_modules/express/lib/router/index.js:312:13)<br> &nbsp; &nbsp;at /Users/sschulthess/other_code/graphiql/example/node_modules/express/lib/router/index.js:280:7<br> &nbsp; &nbsp;at Function.process_params (/Users/sschulthess/other_code/graphiql/example/node_modules/express/lib/router/index.js:330:12)<br> &nbsp; &nbsp;at next (/Users/sschulthess/other_code/graphiql/example/node_modules/express/lib/router/index.js:271:10)<br> &nbsp; &nbsp;at serveStatic (/Users/sschulthess/other_code/graphiql/example/node_modules/express/node_modules/serve-static/index.js:75:16)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/sschulthess/other_code/graphiql/example/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/Users/sschulthess/other_code/graphiql/example/node_modules/express/lib/router/index.js:312:13)<br> &nbsp; &nbsp;at /Users/sschulthess/other_code/graphiql/example/node_modules/express/lib/router/index.js:280:7```

**Comment by scottschulthess** [comment]
This is probably an issue with me using an old version of node
