### ISSUE TITLE
Language server can't open files with special characters

### ISSUE THREAD

**Issue by danielbuechele** [graphql/graphiql#1644]
When a file name has special characters (in my case `[]`) they are escaped and therefor the file can't be found.

```
(node:99747) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/danielbuechele/millone/pages/grinders/%5Bhandle%5D/buy.tsx'
    at Object.openSync (fs.js:447:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:349:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at /Users/danielbuechele/.vscode-fb/extensions/graphql.graphql-vscode-insiders-0.3.5/node_modules/graphql-language-service-server/dist/MessageProcessor.js:293:35
    at Array.map (<anonymous>)
    at MessageProcessor.handleWatchedFilesChangedNotification (/Users/danielbuechele/.vscode-fb/extensions/graphql.graphql-vscode-insiders-0.3.5/node_modules/graphql-language-service-server/dist/MessageProcessor.js:286:43)
    at /Users/danielbuechele/.vscode-fb/extensions/graphql.graphql-vscode-insiders-0.3.5/node_modules/graphql-language-service-server/dist/startServer.js:161:122
(node:99747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
```

**Comment by acao** [comment]
@danielbuechele thanks for this! this might just be a pre-release bug.

does this happen when the extension (and thus the language service server) first initializes? or does it only happen when that file is opened or already open on start?

**Comment by danielbuechele** [comment]
This seems to be happening every time I open the file.

**Comment by acao** [comment]
@danielbuechele did this improve when switching to `prisma.vscode-graphql`? we have some stable releases there now
