### ISSUE TITLE
LSP server triggers unhandled rejection when schema endpoint is unavailable

### ISSUE THREAD

**Issue by rchl** [graphql/graphiql#1711]
With a config file like:

```
module.exports = {
    schema: 'http://localhost:5000/browse/api'
}
```

And the server not actually running, the server will try to connect to the endpoint and trigger promise rejection that is not unhandled:

```
internal/process/warning.js:40 (node:8940) UnhandledPromiseRejectionWarning: FetchError: request to http://localhost:5000/browse/api failed, reason: connect ECONNREFUSED 127.0.0.1:5000
    at ClientRequest.<anonymous> (/Users/me/github/graphiql/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:428:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Unhandled rejections are bad as with Node 14 those will just crash the process.

**Comment by acao** [comment]
thanks for the bug report! hmmm... which version of the LSP server are you using? are you using the CLI or the server directly or the vscode or vim extensions? seems this is coming from `graphql-config` since we don't invoke `node-fetch` ourselves.

**Comment by rchl** [comment]
Starting the server with:
```sh
node graphql-language-service-cli/bin/graphql.js server --method stream`
```
with those dependencies:
```
    "graphql": "^15.0.0",
    "graphql-language-service-cli": "^3.0.1"
```
(also tried the latest version from master)

It looks like the problem is indeed in `graphql-config` and looks like you can't catch that error event (from [here](https://github.com/graphql/graphiql/blob/9ee365ccd6b6433a01d7dbc09a72c0e5a9098673/packages/graphql-language-service-server/src/GraphQLCache.ts#L67).

I suppose I should file an issue on `graphql-config` repo.

> although... i guess because I just implemented auto-reloading when changing the graphql config, it could instead disable all the language server features until the config is changed and a valid schema is present. is that the experience you are expecting?

That sounds better to me then exiting the server as exiting would be hard to understand for the user.
To notify the user about the problem with loading schema, you could probably use `window/showMessage`. Or create diagnostic in opened `gql` file, I guess.

**Comment by acao** [comment]
I was wrong, we can trap any exception we need to and handle this from the server and send a client notification as we should
