### ISSUE TITLE
`GraphQLScalarType` does not respect `extensions.code` value

### ISSUE THREAD

**Issue by AhmedBHameed** [graphql/graphiql#2014]
# Background

I'm using `graphql-scalar` and found a strange behavior which would consider it as a bug maybe?

We are applying `EmailAddress` scalar validation in our input. If the user enters invalid email, we get an error with `extentions.code` equal to `INTERNAL_SERVER_ERROR`. I think that is not a server error but more about `GRAPHQL_VALIDATION_ERROR` or `BAD_USER_INPUT`?

The error is triggered in this [line](https://github.com/Urigo/graphql-scalars/blob/e7d406c987f863bee9df5dc036cf5f72fa654c22/src/scalars/EmailAddress.ts#L48) where if i set the code to `BAD_USER_INPUT` we still got `INTERNAL_SERVER_ERROR`.

I already reported the issue in here https://github.com/Urigo/graphql-scalars/issues/1192

# Actual Behavior

Getting `extendsions.code` as `INTERNAL_SERVER_ERROR` instead of something like `GRAPHQL_VALIDATION_ERROR` or `BAD_USER_INPUT`

# Expected Behavior

I believe that scalar error codes should never be an `INTERNAL_SERVER_ERROR` because simply it is a handler for such an error outside of the `INTERNAL_SERVER_ERROR` scope (unless some cases that i'm not aware of?).

# Steps to Reproduce the Problem Or Description

Here is a minimum reproduce of the issue here
https://codesandbox.io/s/stupefied-mahavira-fe1mr?file=/src/index.js

- Land on `/graphql` to see introspection playground
- Run the query
```gql
mutation {
  forgotPasswordByEmail(email:"ab.com")
}
```

The error will be
```
{
  "error": {
    "errors": [
      {
        "message": "Expected value of type \"EmailAddress!\", found \"ab.com\"; Value is not a valid email address: ab.com",
        "locations": [
          {
            "line": 2,
            "column": 32
          }
        ],
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
          "exception": {
            "stacktrace": [
              "TypeError: Value is not a valid email address: ab.com",
              "    at validate$1 (/sandbox/node_modules/graphql-scalars/index.js:866:15)",
              "    at GraphQLScalarType.parseLiteral (/sandbox/node_modules/graphql-scalars/index.js:880:16)",
              "    at isValidValueNode (/sandbox/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:146:30)",
              "    at Object.StringValue (/sandbox/node_modules/graphql/validation/rules/ValuesOfCorrectTypeRule.js:112:28)",
              "    at Object.enter (/sandbox/node_modules/graphql/language/visitor.js:303:32)",
              "    at Object.enter (/sandbox/node_modules/graphql/utilities/TypeInfo.js:387:27)",
              "    at visit (/sandbox/node_modules/graphql/language/visitor.js:200:21)",
              "    at validate (/sandbox/node_modules/graphql/validation/validate.js:91:24)",
              "    at validate (/sandbox/node_modules/apollo-server-core/dist/requestPipeline.js:185:39)",
              "    at processGraphQLRequest (/sandbox/node_modules/apollo-server-core/dist/requestPipeline.js:90:34)"
            ]
          }
        }
      }
    ]
  }
}
```

# Specifications

OS Name: Linux
Graphql version: `"graphql": "^16.0.1",`
Node version: `14.18.1`

**Comment by AhmedBHameed** [comment]
Oops! wrong repo to report. Sorry.
