### ISSUE TITLE
Language service fails w/ ERR_INVALID_URL_SCHEME after opening config file

### ISSUE THREAD

**Issue by diminutivesloop** [graphql/graphiql#2021]
## Actual Behavior
Language service fails to load w/ an ERR_INVALID_URL_SCHEME error and autocomplete and go-to-definition is not available.

## Expected Behavior
Autocomplete and go-to-definition should be available for graphql query template strings in TypeScript files.

## Steps to Reproduce the Problem Or Description
1. Open a project with a valid GraphQL config file.
2. Open that file in a tab.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.18
  - VSCode Version: 1.61.0
  - OS Name: Mac OS
  - OS Version: 11.6

## Logs Of TS Server || GraphQL Language Service
```10/6/2021, 2:52:30 PM [4] (pid: 98463) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
10/6/2021, 2:52:46 PM [4] (pid: 98463) graphql-language-service-usage-logs: {"type":"usage","messageType":"textDocument/didOpen","projectName":"default","fileName":"file:///Users/nathanielpalmer/projects/ss-ecomm-frontend/src/components/ContentfulPaymentFormComponent/index.tsx"}
10/6/2021, 2:52:49 PM [3] (pid: 98463) graphql-language-service-usage-logs: updating graphql config
(node:98463) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL_SCHEME]: The URL must be of scheme file
    at Object.fileURLToPath (internal/url.js:1352:11)
    at /Users/nathanielpalmer/.vscode/extensions/graphql.vscode-graphql-0.3.18/node_modules/graphql-language-service-server/dist/MessageProcessor.js:353:54
    at Array.map (<anonymous>)
    at MessageProcessor.handleWatchedFilesChangedNotification (/Users/nathanielpalmer/.vscode/extensions/graphql.vscode-graphql-0.3.18/node_modules/graphql-language-service-server/dist/MessageProcessor.js:342:43)
    at /Users/nathanielpalmer/.vscode/extensions/graphql.vscode-graphql-0.3.18/node_modules/graphql-language-service-server/dist/startServer.js:165:122
    at handleNotification (/Users/nathanielpalmer/.vscode/extensions/graphql.vscode-graphql-0.3.18/node_modules/vscode-jsonrpc/lib/main.js:502:43)
    at processMessageQueue (/Users/nathanielpalmer/.vscode/extensions/graphql.vscode-graphql-0.3.18/node_modules/vscode-jsonrpc/lib/main.js:273:17)
    at Immediate._onImmediate (/Users/nathanielpalmer/.vscode/extensions/graphql.vscode-graphql-0.3.18/node_modules/vscode-jsonrpc/lib/main.js:260:13)
    at processImmediate (internal/timers.js:461:21)
(Use `Code Helper (Renderer) --trace-warnings ...` to show where the warning was created)
(node:98463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:98463) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by acao** [comment]
I think I have a resolution finally!

https://github.com/graphql/graphiql/pull/2055

**Comment by acao** [comment]
yup, appears to have resolved the issue for me with many combinations of config. keeping open if there are any hanging issues

**Comment by acao** [comment]
does the latest release seem to be working? i have a few more smaller bugfixes coming along, but this issue in particular should be resolved

**Comment by diminutivesloop** [comment]
Just checked w/ v0.3.30 and I'm not seeing this error anymore.
