### ISSUE TITLE
Regression with graphql-language-service 4.x: "Unexpected token: punc (.)"

### ISSUE THREAD

**Issue by floyd-may** [graphql/graphiql#2090]
This appears to be the same regression from #1833 from an initial glance. I was able to work around it by pinning graphiql to 1.5.7 and codemirror-graphql to 1.2.5.

Stack trace:
```
/root/project/src/frontend/node_modules/graphql-language-service/esm/LanguageService.js: Unexpected token: punc (.)
    at Z.get (/root/project/src/frontend/node_modules/terser/dist/bundle.min.js:1:525)
    at Object.errorToJson (/root/project/src/frontend/node_modules/@parcel/utils/src/errorUtils.js:9:20)
    at Pipeline.process (/root/project/src/frontend/node_modules/parcel-bundler/src/Pipeline.js:29:26)
    at async Object.run (/root/project/src/frontend/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Child.handleRequest (/root/project/src/frontend/node_modules/@parcel/workers/src/child.js:60:26)
```

Using Parcel bundler (as you can see from the bottom of the stack).

**Comment by acao** [comment]
Thank you for reporting! Is the error at the same line at onlineParser again or somewhere else? Any more context? Bundler, etc? A repro on codesandbox/etc if possible?

**Comment by floyd-may** [comment]
Updated above w/ stack trace and bundler info. Sorry, should've done that from the start. Don't know I can easily make a codesandbox to repro, and this is on a closed-source repo. Glad to get more diagnostic info if you can steer me in the right direction.

**Comment by acao** [comment]
Thanks! I will take a closer look after work this week

**Comment by acao** [comment]
this should be fixed now!
