### ISSUE TITLE
graphiql requires the "global" global variable to be defined

### ISSUE THREAD

**Issue by francisu** [graphql/graphiql#2155]
This is not necessarily present in the browser:

https://developer.mozilla.org/en-US/docs/Glossary/Global_object

This causes a runtime error with using graphiql when bundling with the default configuration in either [esbuild]https://esbuild.github.io/ or [Vite]https://vitejs.dev/.

Fix is simple, PR will be provided shortly.

```
GraphiQL.js:661 Uncaught ReferenceError: global is not defined
at GraphiQL2.componentDidMount (GraphiQL.js:661:9)
at commitLifeCycles (react-dom.development.js:20663:24)
at commitLayoutEffects (react-dom.development.js:23426:7)
at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
at invokeGuardedCallback (react-dom.development.js:4056:31)
at commitRootImpl (react-dom.development.js:23151:9)
at unstable_runWithPriority (scheduler.development.js:468:12)
at runWithPriority$1 (react-dom.development.js:11276:10)
at commitRoot (react-dom.development.js:22990:3)
GraphiQL2.componentDidMount @ GraphiQL.js:661
commitLifeCycles @ react-dom.development.js:20663
commitLayoutEffects @ react-dom.development.js:23426
callCallback2 @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309


```

**Comment by Ionshard** [comment]
I am also running into this error when building an application with GraphiQL via an Nx project

**Comment by acao** [comment]
yes we need to get rid of any references to window or global as part of supporting multiple editors in a single document. this is an ancient legacy feature that will be deprecated in 2.x. unfortunately it's an interface used by a lot of projects like graphiql explorer, though maybe they changed their implementation, so this PR will keep it around for them 💯

**Comment by acao** [comment]
Released!

**Comment by francisu** [comment]
This should be reopened, as these PRs broke the fix: https://github.com/graphql/graphiql/pull/2166, https://github.com/graphql/graphiql/pull/2167

**Comment by ianschmitz** [comment]
@acao this is still broken, mind reopening the ticket?

**Comment by carlosrziegler** [comment]
This still broken :( using NX and :
`
"react": "^17.0.2",
"react-dom": "^17.0.2",
`

**Comment by acao** [comment]
In the midst of moving today, can can someone open a quick PR for this? Just need to add `typeof` to the beginning of this expression, i believe?

https://github.com/graphql/graphiql/blob/9458e10ba24a6c919142ea1cebb409c7d055baf9/packages/graphiql/src/components/GraphiQL.tsx#L643

**Comment by acao** [comment]
Fixed in 1.8.3!
