### ISSUE TITLE
Trap `graphql-config` parse errors to prevent the server from crashing

### ISSUE THREAD

**Issue by jer-sen** [graphql/graphiql#2362]
## Actual Behavior
The extension crashes at startup with this error in GraphQL Language Service output:

```UnhandledPromiseRejectionWarning: Error: Field "TypeWithDuplicatedField.duplicatedField" can only be defined once.```

## Expected Behavior
An error reported in "Problems".

## Steps to Reproduce the Problem Or Description
Create a schema with this type:

```
type TypeWithDuplicatedField {
	duplicatedField: Boolean
	duplicatedField: Boolean
}
```

Then in console "Restart Extension Host" and check GraphQL Language Service output.

## Specifications

  - GraphQL for VSCode Extension Version: 0.3.40
  - VSCode Version: 1.62.3
  - OS Name: Windows
  - OS Version: 10
  - graphql config filename and format example:

## Logs Of TS Server || GraphQL Language Service
```
08/12/2021, 15:23:38 [3] (pid: 33104) graphql-language-service-usage-logs: {"type":"usage","messageType":"initialize"}
(node:33104) UnhandledPromiseRejectionWarning: Error: Field "TypeWithDuplicatedField.duplicatedField" can only be defined once.
    at assertValidSDL (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:23096:15)
    at Object.buildASTSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:26602:38)
    at makeExecutableSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:91788:26)
    at Object.mergeSchemas (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:91819:14)
    at Object.loadSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:92349:31)
    at async GraphQLCache.getSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:95089:22)
(Use `Code --trace-warnings ...` to show where the warning was created)
(node:33104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:33104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33104) UnhandledPromiseRejectionWarning: Error: Field "TypeWithDuplicatedField.duplicatedField" can only be defined once.
    at assertValidSDL (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:23096:15)
    at Object.buildASTSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:26602:38)
    at makeExecutableSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:91788:26)
    at Object.mergeSchemas (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:91819:14)
    at Object.loadSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:92349:31)
    at async GraphQLCache.getSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:95089:22)
(node:33104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:33104) UnhandledPromiseRejectionWarning: Error: Field "TypeWithDuplicatedField.duplicatedField" can only be defined once.
    at assertValidSDL (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:23096:15)
    at Object.buildASTSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:26602:38)
    at makeExecutableSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:91788:26)
    at Object.mergeSchemas (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:91819:14)
    at Object.loadSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:92349:31)
    at async GraphQLCache.getSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:95089:22)
(node:33104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:33104) UnhandledPromiseRejectionWarning: Error: Field "TypeWithDuplicatedField.duplicatedField" can only be defined once.
    at assertValidSDL (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:23096:15)
    at Object.buildASTSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:26602:38)
    at makeExecutableSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:91788:26)
    at Object.mergeSchemas (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:91819:14)
    at Object.loadSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:92349:31)
    at async GraphQLCache.getSchema (c:\Users\Blabla\.vscode\extensions\graphql.vscode-graphql-0.3.40\out\server\server.js:95089:22)
(node:33104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by acao** [comment]
@jer-sen this should be fixed now! graphql config errors report to the output channel. eventually we will decide how to show properUI  notifications
