### ISSUE TITLE
RTL warnings in jest/general jest output noise

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#2602]
This warning or a similar one has been happening for some time even before @thomasheyenbrock began work in our earlier unit tests, because of our outdated RTL usage I think?

Somewhere between this and introducing the `@graphiql/react` bundle and `vite` for production usage, it seems that when there are jest warnings we get this huge buffer to stdout we've all probably noticed. Luckily folks working on other parts of the repo can filter these out locally and on the precommit hook, but then still, it makes it harder to find test bugs in CI

```
 console.error
      Warning: An update to SchemaContextProvider inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at SchemaContextProvider (/home/runner/work/graphiql/graphiql/packages/graphiql-react/dist/index.cjs.js:60:4266)
          at EditorContextProvider (/home/runner/work/graphiql/graphiql/packages/graphiql-react/dist/index.cjs.js:60:23863)
          at HistoryContextProvider (/home/runner/work/graphiql/graphiql/packages/graphiql-react/dist/index.cjs.js:58:2056)
          at StorageContextProvider (/home/runner/work/graphiql/graphiql/packages/graphiql-react/dist/index.cjs.js:35:7024)
          at GraphiQLProviders (/home/runner/work/graphiql/graphiql/packages/graphiql/src/components/GraphiQL.tsx:437:5)
          at GraphiQL (/home/runner/work/graphiql/graphiql/packages/graphiql/src/components/GraphiQL.tsx:315:5)
```

**Comment by thomasheyenbrock** [comment]
Some of these were already happening before the refactoring. Moving stuff to vite which outputs a minified build really bloated the warnings.

I would propose to revisit our tests for `graphiql` and `@graphiql/react` in general. We currently only have "high level" tests for the `GraphiQL` component. Most of these tests assert functionality that could be tested more granularly on the provider components. I figure that refactoring and moving the current tests would naturally allow us to remove these warnings piece by piece.

**Comment by acao** [comment]
@thomasheyenbrock indeed:

> This warning or a similar one has been happening for some time even before @thomasheyenbrock began work

also agreed about revisiting the tests, they were almost direct ports from an enzyme suite that we implemented when we migrated to jest from mocha, but the high level GraphiQL tests have always been a smell, and have kept us from having better integration level tests.

**Comment by jonathanawesome** [comment]
I've got a branch locally that has ladle installed in `@graphiql/react` that's helping me to do some visual component testing and file shuffling/organization. I've also got existing testing code [in the prototype](https://github.com/jonathanawesome/graphiql-prototype/blob/main/plugins/graphiql-plugin-pane-pathfinder/src/components/Pathfinder/Pathfinder.test.tsx) that tests a hook through UI components, which could be a nice pattern to use in `@graphiql/react`.

**Comment by jonathanawesome** [comment]
Also, I was tripped up for at least a couple of hours because I was unaware that I needed to add exported modules from `@graphiql/react` to the [mock that `@graphiql` uses](https://github.com/graphql/graphiql/blob/main/packages/graphiql/__mocks__/%40graphiql/react.ts). I haven't much exposure to cypress, is it the reason why modules need to be reexported from the mock?

**Comment by thomasheyenbrock** [comment]
@jonathanawesome the mock file you mentioned is not for Cypress tests but for our unit tests using jest. CodeMirror does not really work in JSDOM, so we mock the editor hooks and components (`QueryEditor`, `useQueryEditor`, etc). The rest of `@graphiql/react` is re-exported as is.

I'm also not super happy with the current state here (it's very easy to forget this). Didn't yet look into how we can selectively mock exports of `@graphiql/react` "globally", i.e. without needing to do it in all test suites separately. I could imaging that reworking the tests and moving them over to `@graphiql/react` would reduce the tests we have in `graphiql` significantly, maybe even completely since we have e2e tests that make sure `graphiql` as a whole works as expected.
