### ISSUE TITLE
[graphiql-react] GraphiQL 2.2.0 not working with webpack projects in React 17

### ISSUE THREAD

**Issue by noelportugal** [graphql/graphiql#2950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running GraphiQL 2.2.0 in a React 17 (17.0.2) project I get the following compiler errors:

```
Compiled with problems:
ERROR in ./node_modules/graphiql/node_modules/@graphiql/react/dist/index.es.js 6297:13-20
export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

ERROR in ./node_modules/graphiql/node_modules/@graphiql/react/dist/index.es.js 6298:14-21
export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
```
![image](https://user-images.githubusercontent.com/882424/205779489-73ea5b7b-b132-46c3-bc14-6ae0195a0161.png)

This appears to be from a react import on the @reach/combo-box library, which gets bundled on the vite build of graphiql. The reach project implements an import guard in their code for auto-ids. Import guards can cause issues with webpack compilations as seen [here](https://github.com/webpack/webpack/issues/14814) and webpack is looking to fix it. As a workaround, reach has updated their [code](https://github.com/reach/reach-ui/commit/78afc3227a94281ff872019524480837950d0d92) with a "safer" guard so that this error wouldn't throw. It appears that this fix is available in v0.18. Currently graphiql is using v0.17 which still has the "unsafe" guard method.
Upgrading the reach libs should hopefully fix the issue on the graphiql side

### Expected Behavior

No error or warning should appear when using GraphiQL 2.2.0 in a React 17 (17.0.2) project.

### Steps To Reproduce

```Markdown
1.- Clone this project [https://github.com/noelportugal/explorer]
2.- cd explorer
3.- `npm install`
4.- `npm run start`
```

### Module pattern

- [ ] graphiql-umd
- [X] graphiql-esm
- [ ] graphiql-commonjs

### Environment

```Markdown
- GraphiQL Version:2.2.0
- OS: Mac Os
- Browser: Chrome
- Bundler:
- `react` Version: 17.0.2
- `graphql` Version: 16.6.0
- `webpack` Version: 5.64.4
```

**Comment by haase1020** [comment]
I am also experiencing the same issue when updating to React 17 and hope the reach libs can be updated to v0.18.

**Comment by zl-sales** [comment]
I also encountered this problem , Then how did you solve it

**Comment by VizTheWiz** [comment]
Same issue with the mentioned versions. If I try to bypass this with an iframe containing an HTML like in the unpkg / jsdelivr examples, I don't get the error. It only pops up in the react app with webpack (But otherwise seems to function properly).

**Comment by CharlieBreval** [comment]
Same problem, I think it s linked to https://github.com/mui/material-ui/issues/29860 but I cannot see the link between graphiql and material-ui
<img width="1105" alt="Capture d’écran 2023-01-07 à 11 05 29" src="https://user-images.githubusercontent.com/1660541/211144955-a4e7561d-205b-4918-a2ac-d8494bb17802.png">

**Comment by ryan-williams** [comment]
Simple repro, attempting to build [examples/graphiql-create-react-app](https://github.com/graphql/graphiql/tree/main/examples/graphiql-create-react-app) in a `node` Docker image:

```Dockerfile
# Dockerfile
FROM node
RUN git clone https://github.com/graphql/graphiql.git
WORKDIR graphiql/examples/graphiql-create-react-app
RUN yarn
RUN yarn build
```

## Build fails: `Cannot find module 'typescript'`
```bash
# bash
echo '*' > .dockerignore
docker build -t graphiql .
```

<details>
<summary>
<code>Error: Cannot find module 'typescript' from '/graphiql/examples/graphiql-create-react-app/node_modules'</code>
</summary>

```
# [+] Building 1.8s (8/8) FINISHED
#  => [internal] load build definition from Dockerfile                                                                                                        0.0s
#  => => transferring dockerfile: 268B                                                                                                                        0.0s
#  => [internal] load .dockerignore                                                                                                                           0.0s
#  => => transferring context: 34B                                                                                                                            0.0s
#  => [internal] load metadata for docker.io/library/node:latest                                                                                              0.0s
#  => [1/5] FROM docker.io/library/node                                                                                                                       0.0s
#  => CACHED [2/5] RUN git clone https://github.com/graphql/graphiql.git                                                                                      0.0s
#  => CACHED [3/5] WORKDIR graphiql/examples/graphiql-create-react-app                                                                                        0.0s
#  => CACHED [4/5] RUN yarn                                                                                                                                   0.0s
#  => ERROR [5/5] RUN yarn build                                                                                                                              1.7s
# ------
#  > [5/5] RUN yarn build:
# #8 0.503 yarn run v1.22.19
# #8 0.543 $ react-scripts build
# #8 1.580 /graphiql/examples/graphiql-create-react-app/node_modules/resolve/lib/sync.js:113
# #8 1.580     throw err;
# #8 1.580     ^
# #8 1.580
# #8 1.580 Error: Cannot find module 'typescript' from '/graphiql/examples/graphiql-create-react-app/node_modules'
# #8 1.580     at Function.resolveSync [as sync] (/graphiql/examples/graphiql-create-react-app/node_modules/resolve/lib/sync.js:111:15)
# #8 1.580     at getModules (/graphiql/examples/graphiql-create-react-app/node_modules/react-scripts/config/modules.js:119:32)
# #8 1.580     at Object.<anonymous> (/graphiql/examples/graphiql-create-react-app/node_modules/react-scripts/config/modules.js:142:18)
# #8 1.580     at Module._compile (node:internal/modules/cjs/loader:1218:14)
# #8 1.580     at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
# #8 1.580     at Module.load (node:internal/modules/cjs/loader:1081:32)
# #8 1.580     at Module._load (node:internal/modules/cjs/loader:922:12)
# #8 1.580     at Module.require (node:internal/modules/cjs/loader:1105:19)
# #8 1.580     at require (node:internal/modules/cjs/helpers:103:18)
# #8 1.580     at Object.<anonymous> (/graphiql/examples/graphiql-create-react-app/node_modules/react-scripts/config/webpack.config.js:28:17) {
# #8 1.580   code: 'MODULE_NOT_FOUND'
# #8 1.580 }
# #8 1.580
# #8 1.580 Node.js v19.3.0
# #8 1.621 error Command failed with exit code 1.
# #8 1.622 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
# ------
# executor failed running [/bin/sh -c yarn build]: exit code: 1
```
</details>

## Add typescript → build fails: `'useId' is not exported from 'react'`
Adding apparently missing typescript/`@types` deps to Dockerfile above:
```diff
 RUN yarn
+RUN yarn add typescript @types/react @types/react-dom
 RUN yarn build
```

```bash
docker build -t graphiql .
```

<details>
<summary><code>Attempted import error: 'useId' is not exported from 'react' (imported as 'useId$1').</code></summary>

```
[+] Building 30.5s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                        0.0s
 => => transferring dockerfile: 267B                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                           0.0s
 => => transferring context: 34B                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/node:latest                                                                                              0.0s
 => [1/6] FROM docker.io/library/node                                                                                                                       0.0s
 => CACHED [2/6] RUN git clone https://github.com/graphql/graphiql.git                                                                                      0.0s
 => CACHED [3/6] WORKDIR graphiql/examples/graphiql-create-react-app                                                                                        0.0s
 => CACHED [4/6] RUN yarn                                                                                                                                   0.0s
 => CACHED [5/6] RUN yarn add typescript @types/react @types/react-dom                                                                                      0.0s
 => ERROR [6/6] RUN yarn build                                                                                                                             30.4s
------
 > [6/6] RUN yarn build:
#9 0.482 yarn run v1.22.19
#9 0.524 $ react-scripts build
#9 1.928 Creating an optimized production build...
#9 29.57 Failed to compile.
#9 29.57
#9 29.57 Attempted import error: 'useId' is not exported from 'react' (imported as 'useId$1').
#9 29.57
#9 29.57
#9 29.90 error Command failed with exit code 1.
#9 29.90 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 1
```
</details>

## `yarn start` / `docker run` fails with a more verbose error message
As in OP:

```diff
 RUN yarn add typescript @types/react @types/react-dom
-RUN yarn build
+ENTRYPOINT ["yarn", "start"]
```
```bash
docker build -t graphiql .
docker run --rm -p 3000:3000 graphiql
```

<details><summary><code>Attempted import error: 'useId' is not exported from 'react' (imported as 'useId$1').</code></summary>

```
yarn run v1.22.19
$ react-scripts start
(node:35) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:35) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

Failed to compile.

Attempted import error: 'useId' is not exported from 'react' (imported as 'useId$1').
ERROR in ./node_modules/@graphiql/react/dist/index.es.js 6297:13-20
export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

ERROR in ./node_modules/@graphiql/react/dist/index.es.js 6298:14-21
export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

webpack compiled with 2 errors
Compiling...
No issues found.
Failed to compile.

Attempted import error: 'useId' is not exported from 'react' (imported as 'useId$1').
ERROR in ./node_modules/@graphiql/react/dist/index.es.js 6297:13-20
export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

ERROR in ./node_modules/@graphiql/react/dist/index.es.js 6298:14-21
export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

webpack compiled with 2 errors
No issues found.
```
</details>

## Same issue at `graphiql@{2.2.0, 2.1.0, 2.0.0,1.11.5}`
I tried similar steps at the tags listed above, and got the same error in all cases.

If anyone has working commands to boot a GraphiQL web app, I'd be interested to see them!

**Comment by luisemz** [comment]
Same issue here:
`export 'useId' (imported as 'useId$1') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)`.
Any work around it?

**Comment by matthewmueller** [comment]
Running into this as well. Any suggestions would be greatly appreciated!

**Comment by maxbaluev** [comment]
Same issue

**Comment by acao** [comment]
> As a workaround, reach has updated their [code](https://github.com/reach/reach-ui/commit/78afc3227a94281ff872019524480837950d0d92) with a "safer" guard so that this error wouldn't throw. It appears that this fix is available in v0.18. Currently graphiql is using v0.17 which still has the "unsafe" guard method.
Upgrading the reach libs should hopefully fix the issue on the graphiql side

huh... `react` is treated as an external by our project, so we need to fix this! thanks for the helpful information @noelportugal

**Comment by acao** [comment]
I'm working on addressing this as part of #2925

**Comment by FollowJack** [comment]
I am enforced to use react 17. Are there any workarounds?

**Comment by ohsnapitscolin** [comment]
For now can we just update the `@reach` deps in `graphiql/react` to use version `0.18.0`? With the [fix](https://github.com/reach/reach-ui/commit/78afc3227a94281ff872019524480837950d0d92) mentioned above I think this should resolve the error.

It seems like not at lot of progress has been made on the vite changes so can we add this in the meantime? I'm unable to use the most recent version of the newest versions of this package otherwise, and those have an important [bug fix](https://github.com/graphql/graphiql/commit/0851d5f9ecf709597d0a698609d88f99c4395665).

**Comment by djnym** [comment]
Just curious where this is, it still seems like you get the warning with recent versions of packages.

**Comment by B2o5T** [comment]
`reach-ui` was completely removed and replaced by radix/headless-ui

for anyone want to give a try alpha version `graphiql@3.0.0-alpha.0`
