### ISSUE TITLE
[vscode-graphql-syntax] /* GraphQL */ does not work but #graphql is work

### ISSUE THREAD

**Issue by comerc** [graphql/graphiql#2982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by comerc** [comment]
case one
<img width="599" alt="Screen Shot 2022-12-23 at 23 23 00" src="https://user-images.githubusercontent.com/1025241/209402752-ea1b7af6-7d44-454a-92e6-61a7a82eb9c5.png">

case two
<img width="540" alt="Screen Shot 2022-12-23 at 23 22 31" src="https://user-images.githubusercontent.com/1025241/209402763-c7a0268c-cd97-4678-99f6-da9cabc802b7.png">

**Comment by holtergram** [comment]
Oh snap, I think I'm having the same error.
Here's the log from the extension host in VSC
```bash
2022-12-24 21:52:59.919 [error] [GraphQL.vscode-graphql] provider FAILED
2022-12-24 21:50:15.990 [error] Error: Request textDocument/hover failed with message: Unexpected token R in JSON at position 0
    at handleResponse (/Users/ME/.vscode/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/common/connection.js:531:48)
    at processMessageQueue (/Users/ME/.vscode/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/common/connection.js:327:17)
    at Immediate.<anonymous> (/Users/ME/.vscode/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/common/connection.js:311:13)
    at processImmediate (node:internal/timers:466:21)
```
Are you also using the `client-preset`?

**Comment by acao** [comment]
this was working. we keep getting regressions in highlighting when people introduce unrelated fixes, and don't have a regression suite for highlighting yet. note that autocomplete and validation still work even though highlighting doesn't
