### ISSUE TITLE
vscode-graphql-execution not running

### ISSUE THREAD

**Issue by acao** [graphql/graphiql#3171]
### Discussed in https://github.com/graphql/graphiql/discussions/3170

<div type='discussions-op-text'>

<sup>Originally posted by **PixeledCode** May 10, 2023</sup>
Attaching the screenshot. I have the latest extension installed, noticed I was not getting any codelens in `.graphql` files. Language Feature and Syntax Highlighting are working as expected.
I also do not see any log for `vscode-graphql-execution`. Is that normal?

<img width="1359" alt="Screenshot 2023-05-10 at 2 25 37 PM" src="https://github.com/graphql/graphiql/assets/22215209/fbc23bd5-b96d-447e-b066-f5b49c635482">
</div>

**Comment by gastonmorixe** [comment]
related?  opened vscode from terminal and log debug mode `code --log debug .` 

<img width="1250" alt="image" src="https://github.com/graphql/graphiql/assets/637225/d1129417-c5d1-4a89-b644-2b0ed9746d21">

**Comment by acao** [comment]
can you show your relevant graphql config entries?

**Comment by gastonmorixe** [comment]
@acao Oh, I don't have any configuration file. 

May [GraphQL: Language Feature Support](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) conflict with [Apollo GraphQL Extension](https://marketplace.visualstudio.com/items?itemName=orsenkucher.vscode-graphql) ?

**Comment by acao** [comment]
@gastonmorixe our extension uses graphql config files, which are different from apollo config files. Their extension provides some of the same features as ours. See the docs to learn how to configure your graphql config file. Most graphql developers use one or the other, but not both together. As you'll see in the readme, the framework/platform agnostic graphql config file is required to use either our execution extension or the full language extension

**Comment by gastonmorixe** [comment]
@acao Great thank you

**Comment by acao** [comment]
ah, this must be related to the esbuild upgrade then

**Comment by nermolov** [comment]
Can confirm, experiencing the same error on current `main` 57b5fcd8749bd1c54f4a6a04a9ab07316fd05e71

```
2023-09-09 14:15:58.268 [error] Activating extension GraphQL.vscode-graphql-execution failed due to an error:
2023-09-09 14:15:58.268 [error] TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
	at new NodeError (node:internal/errors:387:5)
	at createRequire (node:internal/modules/cjs/loader:1308:11)
	at Object.<anonymous> (/home/nik/playground/applications/graphiql/packages/vscode-graphql-execution/out/extension.js:505954:48)
	at Module._compile (node:internal/modules/cjs/loader:1188:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at o._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:28084)
	at f._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:25418)
	at C._load (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:19511)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:5:98)
	at r.rb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:130:26597)
	at async Promise.all (index 0)
```
