### ISSUE TITLE
[vscode-graphql] "Server crashed 5 times in the last 3 minutes" because watcher is looking at unwanted directories

### ISSUE THREAD

**Issue by murtlatif** [graphql/graphiql#3459]
## Problem

I'm using Sapling SCM instead of Git, and it has a `.sl/` folder which can often contain files that have a very short lifespan.

My extension crashes quickly because the watcher is looking at this directory, since it's not ignored by default like `.git` is, and it often comes across this error:

```
Error: ENOENT: no such file or directory, open '/home/murt/my_code/.sl/runlog/abc.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at readFileSync (node:fs:471:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9212)
    at /home/murt/.vscode/extensions/graphql.vscode-graphql-0.8.19/out/server/index.js:4635:5136
    at Array.map (<anonymous>)
    at QGe.handleWatchedFilesChangedNotification (/home/murt/.vscode/extensions/graphql.vscode-graphql-0.8.19/out/server/index.js:4635:4844)
    at /home/murt/.vscode/extensions/graphql.vscode-graphql-0.8.19/out/server/index.js:4669:103056
    at Z (/home/murt/.vscode/extensions/graphql.vscode-graphql-0.8.19/out/server/index.js:4644:1611)
    at G (/home/murt/.vscode/extensions/graphql.vscode-graphql-0.8.19/out/server/index.js:4643:6757) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/murt/my_code/.sl/runlog/abc.json'
}

Node.js v18.15.0
[Error - 12:29:30 PM] The vscode-graphql server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Info  - 12:29:30 PM] The graphql server has stopped running
```

I'm currently using the latest versions of the extensions:

- GraphQL: Language Feature Support `v0.8.19`
- GraphQL: Syntax Highlighting: `v1.2.2`

## Potential Solution

I locally built the extension by modifying the `workspace.createFileSystemWatcher` to take in my hardcoded workspace path excluding the `.sl` folder, but this is obviously not the correct long term solution since I would need to redo this each time there's an update if I want to keep the latest version.

I think we could add a VSCode setting to exclude specific file paths from the watcher, or alternatively specify the base path to watch from.

I unfortunately don't have too much time to create a PR for a proper solution but I think it's at least worth noting the issue here.

**Comment by acao** [comment]
graphql config already has exclude rules, did you try those to see if they help? you can set them per project, or for the default project of there is only one

**Comment by murtlatif** [comment]
Unfortunately the graphql config `exclude` rules don't help here - if I'm not mistaken, this seems to be at the extension language client layer and is before the language server is even involved ([code reference]( https://github.com/graphql/graphiql/blob/main/packages/vscode-graphql/src/extension.ts#L78-L79)).

I gave it a try anyway and I do still get the same issue.

**Comment by acao** [comment]
the error is being thrown by the LSP server:

>     at /home/murt/.vscode/extensions/graphql.vscode-graphql-0.8.19/out/server/index.js:4669:103056
>    at Z (/home/murt/.vscode/extensions/graphql.vscode-graphql-0.8.19/out/server/index.js:4644:1611)
>    at G (/home/murt/.vscode/extensions/graphql.vscode-graphql-0.8.19/out/server/index.js:4643:6757) {

**Comment by murtlatif** [comment]
You're right, it does seem like the error is coming from the server handling the notification and not from the client or watcher.

Also, I want to bottom out on the `exclude` config, just in case I'm doing something incorrectly there. I've tried all of the following in my `.graphqlrc.yml` files:
```yml
projects:
  app_1:
    schema: "../schema.graphql"
    exclude: "/.sl"
  app_2:
    schema: "../schema.graphql"
    exclude: "/.sl"
```

I've tried the following for the `exclude:` field:
- `".sl/"`
- `".sl/**/*"`
- `"/.sl/"`
- `"/.sl/**/*"`
- `"**/.sl/**/*"`

I'm not fully sure what the correct glob to use is here but wanted to note this in case I do have an incorrect path.

**Comment by acao** [comment]
Yes, those are correct globs for Minimatch that graphql config uses. the likely issue is with our LSP internal method I referenced above, where include and exclude is not accounted for

**Comment by acao** [comment]
Ah! I see the update in the title. That is useful to know. I think we need to handle the delete event and remove them from the cache, as well as what I was suggesting

**Comment by murtlatif** [comment]
That's understandable, however I think it may be worthwhile to consider providing some flexibility for what directories are being watched anyway for two reasons:
1. Prevent unnecessary processing of potentially large amounts of file events for irrelevant files
2. Can potentially be an easy interim fix for this problem (although I do agree that the file events should be handled properly, and just not watching the file in this case would be just a bandaid fix)

**Comment by murtlatif** [comment]
Ah, that's my mistake - I was thinking of the exclude rules being for a slightly different layer, but this makes sense. Thanks @acao!

**Comment by murtlatif** [comment]
Any plans to tackle this issue? It would be nice to be able to use this tool with other VCS, since it's completely unusable for me at the moment.

No expectation here since I can understand this problem may be only applicable to a really tiny subset of users - just want to know if I should keep an eye on upcoming updates

**Comment by acao** [comment]
I do plan to tackle this issue, yes!
