### ISSUE TITLE
[lsp-server] 🐞 Pending response rejected since connection got disposed

### ISSUE THREAD

**Issue by M1CK431** [graphql/graphiql#3547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Server crash with stacktrace:
```
Node.js v18.17.1
[Error - 14:12:42] The vscode-graphql server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
Initialization failed
Pending response rejected since connection got disposed
Error: Pending response rejected since connection got disposed
	at Object.dispose (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:29:4460)
	at Object.dispose (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:39:22314)
	at Ll.handleConnectionClosed (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:39:12275)
	at Ll.handleConnectionClosed (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:39:50478)
	at t (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:39:11956)
	at ia.invoke (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:2:14331)
	at n.fire (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:2:15100)
	at Lt (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:3:6456)
	at ia.invoke (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:2:14331)
	at n.fire (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:2:15100)
	at Pa.fireClose (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:2:17355)
	at ChildProcess.<anonymous> (/home/user/.vscode-oss/extensions/graphql.vscode-graphql-0.9.2-universal/out/extension.js:29:13076)
	at ChildProcess.emit (node:events:526:35)
	at maybeClose (node:internal/child_process:1091:16)
	at Process.onexit (node:internal/child_process:302:5)
[Error - 14:12:42] vscode-graphql client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 14:12:42] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097
```

### Expected Behavior

LSP server start!

### Steps To Reproduce

Just install GraphQL: Language Feature Support v0.9.2 and restart vscode

### Environment

* LSP Server Version: 0.9.2
* OS: Archlinux
* LSP Client: vscode 1.87.0 (oss edition)

### Anything else?

running `npm i` in the extension folder workaround the issue so seems to be the same root cause as #3516

**Comment by acao** [comment]
is this via ovsx or vscode marketplace?

**Comment by M1CK431** [comment]
ovsx.

> There is a known issue with OVSX that we still need to fix.

Interesting! Do you have a link? 🙏🏼

**Comment by acao** [comment]
@M1CK431 even better, I have a new release for you to try! Please let me know if 0.9.3 fixes that issue at least

**Comment by M1CK431** [comment]
You are the best! It works now 👏🏼 🎉 🍾 🏆 🥇
