### ISSUE TITLE
Default value of negative infinity for args breaks schema definitions

### ISSUE THREAD

**Issue by tsiege** [graphql/graphiql#481]
When I was writing a custom connection, I added a field to `args` with a `defaultValue` of `-Infinity`, which ended up breaking the schema generation. I was still able to query the Graph API via graphiql, but I received this error message and had no access to documentation.

```
GraphQLError
    at r (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:549156)
    at d (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:290786)
    at p (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:290452)
    at u (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:289639)
    at Object.i [as advance] (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:287893)
    at ee (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:251214)
    at i (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:243452)
    at S (https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:560024)
    at https://cdn.bustle.com/graphiql/production/assets/main-0857f510922c.js:1:286709
    at Array.reduce (native)
```

my code looked like this
```js
...
args: Object.assign({
  min: {
    type: GraphQLFloat, defaultValue: -Infinity
  },
}, connectionArgs),
...
```

**Comment by AGS-** [comment]
@TSiege, sorry for taking so long to respond, let me check this out with @wincent @asiandrummer

**Comment by TSiege** [comment]
No problem. Let me know if you need any other context

**Comment by asiandrummer** [comment]
@TSiege again sorry for taking long time to respond - is there a way to get a more useful stack trace?
I'm guessing that `-Infinity` isn't supported as the default value as [this code from `graphql-js`](https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L19-L20) expresses the infinity value as actual numbers. It'd be clearer if we could get an actual stack trace along with the error message.

**Comment by thomasheyenbrock** [comment]
Positive and negative infinity are not valid values for a `Float` in GraphQL, see https://spec.graphql.org/draft/#sec-Float

If one defines `defaultValue: -Infinity` anyways, the latest version of GraphQL returns an error as part of introspection, while the rest of the schema data is valid. By that, GraphiQL also does not break and works as if there would be no default value.
