### ISSUE TITLE
Attributes with  multi-dimensional array with non-optional elements crash

### ISSUE THREAD

**Issue by lightsprint09** [graphql/graphiql#541]
If we have a type which contains a multi-dimensional array with non-optional elements like the following:

```
type GeoPolygon {
    type: String!
    coordinates: [[[[Float!]!]!]!]!
}
```

we  get the following errors:
**Safari Version 10.1.1 (12603.2.4)**
```
Error: Decorated type deeper than introspection query.
    at n (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11613)
    at n (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11855)
    at n (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11709)
    at n (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11855)
    at n (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11709)
    at n (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11855)
    at n (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11709)
    at n (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11855)
    at r (http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:12401)
    at http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:14583
```

**Chrome Version 59.0.3071.115 (Official Build) (64-Bit)**
```
n@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11622
n@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11856
n@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11710
n@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11856
n@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11710
n@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11856
n@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11710
n@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:11856
r@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:12402
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:14584
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:13:13483
reduce@[native code]
defineFieldMap@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:14:16204
getFields@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:14:22042
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22064
typeMapReducer@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22227
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22214
forEach@[native code]
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22089
typeMapReducer@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22227
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22214
forEach@[native code]
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22089
typeMapReducer@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22227
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22214
forEach@[native code]
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22089
typeMapReducer@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22227
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22214
forEach@[native code]
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22089
typeMapReducer@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22227
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22214
forEach@[native code]
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22089
typeMapReducer@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22227
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22214
forEach@[native code]
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22089
typeMapReducer@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:22227
reduce@[native code]
e@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:15:25294
buildClientSchema@http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:16:16141
http://cdn.jsdelivr.net/graphiql/0.10.1/graphiql.min.js:2:15528
promiseReactionJob@[native code]
```

**Comment by asiandrummer** [comment]
Hi @lightsprint09 - this happens because `graphql-js` doesn't support [a very deep decoration of types](https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/buildClientSchema-test.js#L749). I'm assuming you've done the decoration as described to meet your specific need, but is there a way that you could maybe refactor the decorated type to be less than 7 levels deep?

**Comment by acao** [comment]
Closing this as it's  a shortcoming of `graphql-js` and not `graphiql`
