### ISSUE TITLE
yarn tries to run prepublish script and fails

### ISSUE THREAD

**Issue by kevinsimper** [graphql/graphiql#633]
```bash
$ yarn
yarn install v1.2.1
warning You are using Node "9.1.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ . ./resources/prepublish.sh
[eval]:1
process.exit(({"remain":[],"cooked":["install"],"original":[]}).original[0].indexOf('pu') === 0)
                                                                            ^

TypeError: Cannot read property 'indexOf' of undefined
    at [eval]:1:77
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:152:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:641:30)
    at evalScript (bootstrap_node.js:470:27)
    at startup (bootstrap_node.js:167:9)
    at bootstrap_node.js:613:3



   Only Travis CI can publish to NPM.
  Ensure git is left is a good state by backing out any commits and deleting any tags.
  Then read CONTRIBUTING.md to learn how to publish to NPM.



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by asiandrummer** [comment]
When running `yarn`, `$npm_config_argv` would be an empty array. I've put in a simple fix to work around this issue in a4d9732318a753deec37929cfbfd4a1719507468. Thanks for the report @kevinsimper
