### ISSUE TITLE
Unexpected Name "null" in graphiql

### ISSUE THREAD

**Issue by olegBryukhanov** [graphql/graphiql#648]
I tried to tune graphiql for project and found out that graphql returns not expected result in 2.0.0-alpha-820 version.

In 0.17.3 version for the first graphiql request it returns something similar to 
```
......
                {
                    "name": "include",
                    "description": "Directs the executor to include this field or fragment only when the 'if' argument is true.",
                    "locations": [
                        "FIELD",
                        "FRAGMENT_SPREAD",
                        "INLINE_FRAGMENT"
                    ],
                    "args": [
                        {
                            "name": "if",
                            "description": "Included when true.",
                            "type": {
                                "kind": "NON_NULL",
                                "name": null,
                                "ofType": {
                                    "kind": "SCALAR",
                                    "name": "Boolean",
                                    "ofType": null
                                }
                            },
                            "defaultValue": "null"
                        }
                    ]
                }
.....
```
where ``` "defaultValue": "null"``` is with quotes and graphiql works well

in 2.0.0-alpha-820

```
.....
                {
                    "name": "include",
                    "description": "Directs the executor to include this field or fragment only when the 'if' argument is true.",
                    "locations": [
                        "FIELD",
                        "FRAGMENT_SPREAD",
                        "INLINE_FRAGMENT"
                    ],
                    "args": [
                        {
                            "name": "if",
                            "description": "Included when true.",
                            "type": {
                                "kind": "NON_NULL",
                                "name": null,
                                "ofType": {
                                    "kind": "SCALAR",
                                    "name": "Boolean",
                                    "ofType": null
                                }
                            },
                            "defaultValue": null
                        }
                    ]
                }
.....
```
where ```"defaultValue": null``` is without quotes 
and that is why graphiql returns an error

```
GraphQLError: Syntax Error GraphQL (1:1) Unexpected Name "null"

1: null
   ^

    at syntaxError (http://localhost:5000/bundle.js:26154:16)
    at unexpected (http://localhost:5000/bundle.js:24515:34)
    at parseValueLiteral (http://localhost:5000/bundle.js:23979:10)
    at parseValue (http://localhost:5000/bundle.js:23593:16)
    at buildInputValue (http://localhost:5000/bundle.js:33858:119)
    at http://localhost:5000/bundle.js:33957:32
    at Array.reduce (<anonymous>)
    at keyValMap (http://localhost:5000/bundle.js:33956:16)
    at buildInputValueDefMap (http://localhost:5000/bundle.js:33851:37)
    at buildDirective (http://localhost:5000/bundle.js:33875:14)
```

I think, it is a bug.

Full responses are in these files

[0.17.3.response.txt](https://github.com/graphql/graphiql/files/1629274/0.17.3.response.txt)
[2.0-alpha.response.txt](https://github.com/graphql/graphiql/files/1629275/2.0-alpha.response.txt)

**Comment by olegBryukhanov** [comment]
Sorry. Wrong repository)

**Comment by AnthonyMeaux101** [comment]
Thanks
