### ISSUE TITLE
Error: Response not successful: Received status code 400

### ISSUE THREAD

**Issue by joeflack4** [graphql/graphiql#700]
## Current behavior
When I open GraphiQL and click "Schema", nothing loads. The console shows the following:
```
(index):1 Failed to load resource: the server responded with a status of 400 (Bad Request)
Playground.tsx:269 Error: Response not successful: Received status code 400
    at c (index.js:28)
    at index.js:53
```

## Expected behavior
Instead of a generic error 400, I would like GraphiQL to display an error message of what is or might be causing the issue, if that is possible.

## Background information

**Update:**  
I discovered what the source of the error was the various errors like the following:
> `The type of Mutation.CreateCorneaThicknessCorrectionLeft(reported_by:) must be Input Type but got: Person.`

Removing all such issues also removed error 400 when accessing "Schema". However, given that it is only possible to see these error messages when making a query to the API, it would be better to display a validation console error either before or after clicking "Schema", rather than error 400.

---

As dependencies, I am using some of the following:
- the function `neo4jgraphql` from `neo4j-graphql-js` to auto-generate resolvers.
- `makeExecutableSchema` from `apollo-server`.
- `augmentSchema` from `neo4j-graphql-js` to auto-generate mutations.

I'm actually getting some warnings showing up in my shell when running the server. These are both related to use of `neo4j-graphql-js`, and I've filed issues accordingly.

> The best way is to provide a reduced test case on jsFiddle or jsBin.  

I wouldn't mind doing this, but I'm not really sure what to do. If you can explain a short list of the steps I should take to set up the server, with dependencies, on either jsFiddle or jsBin, I promise that I will do this.

Also, I'm using the [grand-stack-starter](https://github.com/grand-stack/grand-stack-starter/tree/master/api) as my base, and I haven't yet added much code since cloning it.

## Code snippets  
I'll show code snippets for the two relevant files, then an output of the shell warnings, and a GraphiQL error showing up in the right half of the GUI when I try to query the API.

### File 1 - `graphql-schema.js`  
```
import gql from "graphql-tag";
import { print } from 'graphql/language/printer'
import { neo4jgraphql } from "neo4j-graphql-js";

export const typeDefs = print(gql`

# Simple Types
scalar Date
scalar DateTime
scalar Email
scalar PhoneNumber
scalar ZeroToOne

enum state_code {
  AL
  AndSoOn # TODO
}

# People
interface Person {
  id: ID!
  person_name_first: String
  person_name_last: String
  person_name_middle: String
  person_name_suffix: String
  person_name_prefix: String
  person_dob: DateTime
}

interface ContactInfo {
  id: ID!
  contact_address_street: String
  contact_address_city: String
  contact_address_state: String
  contact_address_country: String
  contact_emails: [Email]
  contact_phones: [PhoneNumber]
}

type Contact implements Person & ContactInfo {
  id: ID!
  person_name_first: String
  person_name_last: String
  person_name_middle: String
  person_name_suffix: String
  person_name_prefix: String
  person_dob: DateTime
  contact_address_street: String
  contact_address_city: String
  contact_address_state: String
  contact_address_country: String
  contact_emails: [Email]
  contact_phones: [PhoneNumber]
  contacts(first: Int = 10, offset: Int = 0): [User] @relation(name: "PERSONAL_CONTACT", direction: "BOTH")
}

type User implements Person & ContactInfo {
  id: ID!
  username: String!
  password: String!  # Handle auth otherwise: https://blog.apollographql.com/a-guide-to-authentication-in-graphql-e002a4039d1
  person_name_first: String
  person_name_last: String
  person_name_middle: String
  person_name_suffix: String
  person_name_prefix: String
  person_dob: DateTime
  contact_address_street: String
  contact_address_city: String
  contact_address_state: String
  contact_address_country: String
  contact_emails: [Email!]
  contact_phones: [PhoneNumber]
  contacts(first: Int = 10, offset: Int = 0): [User] @relation(name: "PERSONAL_CONTACT", direction: "BOTH")
}

# Afflictions
interface Illness {
  id: ID!
  illness_name: String
  illness_description: String
  illness_date_onset: String
}

interface Diagnosis {
  id: ID!
  diagnosis_name: String
  diagnosis_description: String
  diagnosis_given_date: String
  diagnosis_given_by_id: ID # to doctor
}

type AfflictionGlaucoma implements Illness & Diagnosis {
  id: ID!
  illness_name: String
  illness_description: String
  illness_date_onset: String
  diagnosis_name: String
  diagnosis_description: String
  diagnosis_given_date: String
  diagnosis_given_by_id: ID # to doctor
}

# Symptoms
# - make a type for every symptom or just one type w/ props?
interface Symptom {
  id: ID!
  name: String
  description: String
}

interface SymptomExperienced {
  id: ID! # is this id of the instance, or symptom type class?
  by: ID! # can I pass this in? not auto-generated?
  name: String
  description: String
  when: DateTime! # dateTime
  adversity_self_ranked_ascending: ZeroToOne!  # default step size should be 0.1; so a range of 10.
  comorbidities: [ID!]
}

type SymptomDizziness {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type EyePain {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type NightHalos {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type TunnelVision {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type BlurredVision {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type SwellingAndRedness {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type AccompanyingNausea {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type SuddenVisualDisturbance {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

# Measurements
interface Measurement {
  id: ID!
  measurement: Float!
  measurement_units: String!
  measured_by: Person
}

interface DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type ReadingBloodPressure implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type IopLeft implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type IopRight implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type CorneaThicknessLeft implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type CorneaThicknessRight implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type CorneaThicknessCorrectionLeft implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type CorneaThicknessCorrectionRight implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type Query {
    # person(id: ID, first: Int = 10, offset: Int = 0): [Person]
    # contactinfo(id: ID, first: Int = 10, offset: Int = 0): [ContactInfo]
    contact(id: ID, first: Int = 10, offset: Int = 0): [Contact]
    user(id: ID, first: Int = 10, offset: Int = 0): [User]
    # illness(id: ID, first: Int = 10, offset: Int = 0): [Illness]
    # diagnosis(id: ID, first: Int = 10, offset: Int = 0): [Diagnosis]
    afflictionglaucoma(id: ID, first: Int = 10, offset: Int = 0): [AfflictionGlaucoma]
    # symptom(id: ID, first: Int = 10, offset: Int = 0): [Symptom]
    # symptomexperienced(id: ID, first: Int = 10, offset: Int = 0): [SymptomExperienced]
    symptomdizziness(id: ID, first: Int = 10, offset: Int = 0): [SymptomDizziness]
    eyepain(id: ID, first: Int = 10, offset: Int = 0): [EyePain]
    nighthalos(id: ID, first: Int = 10, offset: Int = 0): [NightHalos]
    tunnelvision(id: ID, first: Int = 10, offset: Int = 0): [TunnelVision]
    blurredvision(id: ID, first: Int = 10, offset: Int = 0): [BlurredVision]
    swellingandredness(id: ID, first: Int = 10, offset: Int = 0): [SwellingAndRedness]
    accompanyingnausea(id: ID, first: Int = 10, offset: Int = 0): [AccompanyingNausea]
    suddenvisualdisturbance(id: ID, first: Int = 10, offset: Int = 0): [SuddenVisualDisturbance]
    # measurement(id: ID, first: Int = 10, offset: Int = 0): [Measurement]
    # diagnosticmeasurementreading(id: ID, first: Int = 10, offset: Int = 0): [DiagnosticMeasurementReading]
    readingbloodpressure(id: ID, first: Int = 10, offset: Int = 0): [ReadingBloodPressure]
    iopleft(id: ID, first: Int = 10, offset: Int = 0): [IopLeft]
    iopright(id: ID, first: Int = 10, offset: Int = 0): [IopRight]
    corneathicknessleft(id: ID, first: Int = 10, offset: Int = 0): [CorneaThicknessLeft]
    corneathicknessright(id: ID, first: Int = 10, offset: Int = 0): [CorneaThicknessRight]
    corneathicknesscorrectionleft(id: ID, first: Int = 10, offset: Int = 0): [CorneaThicknessCorrectionLeft]
    corneathicknesscorrectionright(id: ID, first: Int = 10, offset: Int = 0): [CorneaThicknessCorrectionRight]

    userBySubstringOfName(substring: String, first: Int = 10, offset: Int = 0): [User] @cypher(statement: "MATCH (u:User) WHERE u.name CONTAINS $substring RETURN u")
}
`);

export const resolvers = {
  Query: {
    // person: neo4jgraphql,
    // contactinfo: neo4jgraphql,
    contact: neo4jgraphql,
    user: neo4jgraphql,
    // illness: neo4jgraphql,
    // diagnosis: neo4jgraphql,
    afflictionglaucoma: neo4jgraphql,
    // symptom: neo4jgraphql,
    // symptomexperienced: neo4jgraphql,
    symptomdizziness: neo4jgraphql,
    eyepain: neo4jgraphql,
    nighthalos: neo4jgraphql,
    tunnelvision: neo4jgraphql,
    blurredvision: neo4jgraphql,
    swellingandredness: neo4jgraphql,
    accompanyingnausea: neo4jgraphql,
    suddenvisualdisturbance: neo4jgraphql,
    // measurement: neo4jgraphql,
    // diagnosticmeasurementreading: neo4jgraphql,
    readingbloodpressure: neo4jgraphql,
    iopleft: neo4jgraphql,
    iopright: neo4jgraphql,
    corneathicknessleft: neo4jgraphql,
    corneathicknessright: neo4jgraphql,
    corneathicknesscorrectionleft: neo4jgraphql,
    corneathicknesscorrectionright: neo4jgraphql,
    userBySubstringOfName: neo4jgraphql,
  }
};
```

### File 2 - `index.js`  
```
import { typeDefs, resolvers } from "./graphql-schema";
import { ApolloServer, makeExecutableSchema } from "apollo-server";
import { v1 as neo4j } from "neo4j-driver";
import { augmentSchema } from "neo4j-graphql-js";
import dotenv from "dotenv";

dotenv.config();

const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
  resolverValidationOptions: {
    requireResolversForResolveType: false
  }
});

const augmentedSchema = augmentSchema(schema);

const driver = neo4j.driver(
  process.env.NEO4J_URI || "bolt://localhost:7687",
  neo4j.auth.basic(
    process.env.NEO4J_USER || "neo4j",
    process.env.NEO4J_PASSWORD || "neo4j"
  )
);

const server = new ApolloServer({
  context: { driver },
  schema: augmentedSchema
});

server.listen(process.env.GRAPHQL_LISTEN_PORT, '0.0.0.0').then(({ url }) => {
  console.log(`GraphQL API ready at ${url}`);
});
```

#### Terminal output  
```
> nodemon --exec babel-node src/index.js

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/index.js`
Type "Person" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "ContactInfo" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Illness" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Diagnosis" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Symptom" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "DiagnosticMeasurementReading" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Measurement" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "SymptomExperienced" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
`onTypeConflict` is deprecated. Use schema transforms to customize merging logic.
GraphQL API ready at http://0.0.0.0:4000/
[nodemon] restarting due to changes...
[nodemon] starting `babel-node src/index.js`
```

#### GraphiQL GUI errors when querying
**Update: ** Discovered this is what was also causing error 400 when trying to show Schema. Elaborated on further near the top in "**Background information**".
```
{
  "error": {
    "errors": [
      {
        "message": "The type of Mutation.CreateSymptomDizziness(comorbidities:) must be Input Type but got: Symptom.\n\nThe type of Mutation.CreateEyePain(comorbidities:) must be Input Type but got: Symptom.\n\nThe type of Mutation.CreateNightHalos(comorbidities:) must be Input Type but got: Symptom.\n\nThe type of Mutation.CreateTunnelVision(comorbidities:) must be Input Type but got: Symptom.\n\nThe type of Mutation.CreateBlurredVision(comorbidities:) must be Input Type but got: Symptom.\n\nThe type of Mutation.CreateSwellingAndRedness(comorbidities:) must be Input Type but got: Symptom.\n\nThe type of Mutation.CreateAccompanyingNausea(comorbidities:) must be Input Type but got: Symptom.\n\nThe type of Mutation.CreateSuddenVisualDisturbance(comorbidities:) must be Input Type but got: Symptom.\n\nThe type of Mutation.CreateReadingBloodPressure(reported_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateReadingBloodPressure(experienced_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateReadingBloodPressure(measured_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateIopLeft(reported_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateIopLeft(experienced_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateIopLeft(measured_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateIopRight(reported_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateIopRight(experienced_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateIopRight(measured_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessLeft(reported_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessLeft(experienced_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessLeft(measured_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessRight(reported_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessRight(experienced_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessRight(measured_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessCorrectionLeft(reported_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessCorrectionLeft(experienced_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessCorrectionLeft(measured_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessCorrectionRight(reported_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessCorrectionRight(experienced_by:) must be Input Type but got: Person.\n\nThe type of Mutation.CreateCorneaThicknessCorrectionRight(measured_by:) must be Input Type but got: Person.",
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "Error: The type of Mutation.CreateSymptomDizziness(comorbidities:) must be Input Type but got: Symptom.",
              "",
              "The type of Mutation.CreateEyePain(comorbidities:) must be Input Type but got: Symptom.",
              "",
              "The type of Mutation.CreateNightHalos(comorbidities:) must be Input Type but got: Symptom.",
              "",
              "The type of Mutation.CreateTunnelVision(comorbidities:) must be Input Type but got: Symptom.",
              "",
              "The type of Mutation.CreateBlurredVision(comorbidities:) must be Input Type but got: Symptom.",
              "",
              "The type of Mutation.CreateSwellingAndRedness(comorbidities:) must be Input Type but got: Symptom.",
              "",
              "The type of Mutation.CreateAccompanyingNausea(comorbidities:) must be Input Type but got: Symptom.",
              "",
              "The type of Mutation.CreateSuddenVisualDisturbance(comorbidities:) must be Input Type but got: Symptom.",
              "",
              "The type of Mutation.CreateReadingBloodPressure(reported_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateReadingBloodPressure(experienced_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateReadingBloodPressure(measured_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateIopLeft(reported_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateIopLeft(experienced_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateIopLeft(measured_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateIopRight(reported_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateIopRight(experienced_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateIopRight(measured_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessLeft(reported_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessLeft(experienced_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessLeft(measured_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessRight(reported_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessRight(experienced_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessRight(measured_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessCorrectionLeft(reported_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessCorrectionLeft(experienced_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessCorrectionLeft(measured_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessCorrectionRight(reported_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessCorrectionRight(experienced_by:) must be Input Type but got: Person.",
              "",
              "The type of Mutation.CreateCorneaThicknessCorrectionRight(measured_by:) must be Input Type but got: Person.",
              "    at assertValidSchema (/Users/joeflack4/projects/hh-api/node_modules/graphql/type/validate.js:71:11)",
              "    at Object.validate (/Users/joeflack4/projects/hh-api/node_modules/graphql/validation/validate.js:54:35)",
              "    at Promise.resolve.then (/Users/joeflack4/projects/hh-api/node_modules/apollo-server-core/src/runQuery.ts:188:30)",
              "    at <anonymous>",
              "    at process._tickCallback (internal/process/next_tick.js:160:7)"
            ]
          }
        }
      }
    ]
  }
}
```

**Comment by dimaMachina** [comment]
Closing due to inactivity. Feel free to reply if you still need help.
