### ISSUE TITLE
window is not defined in SSR mode @0.14.0

### ISSUE THREAD

**Issue by Fi1osof** [graphql/graphiql#942]
See title. @0.13.2 all OK

```
(node:22785) ExperimentalWarning: The ESM module loader is experimental.
18|uae-realty-front:3820  | modules/Avatar deprecated. Use ui/Avatar instead
18|uae-realty-front:3820  | ReferenceError: window is not defined
18|uae-realty-front:3820  |     at Object.<anonymous> (/var/www/uae/uae-realty/node_modules/graphiql/dist/utility/commonKeys.js:12:15)
18|uae-realty-front:3820  |     at Module._compile (internal/modules/cjs/loader.js:688:30)
18|uae-realty-front:3820  |     at Module._compile (/var/www/uae/uae-realty/node_modules/pirates/lib/index.js:99:24)
18|uae-realty-front:3820  |     at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
18|uae-realty-front:3820  |     at Object.newLoader [as .js] (/var/www/uae/uae-realty/node_modules/pirates/lib/index.js:104:7)
18|uae-realty-front:3820  |     at Module.load (internal/modules/cjs/loader.js:598:32)
18|uae-realty-front:3820  |     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
18|uae-realty-front:3820  |     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
18|uae-realty-front:3820  |     at Module.require (internal/modules/cjs/loader.js:636:17)
18|uae-realty-front:3820  |     at require (internal/modules/cjs/helpers.js:20:18)

```

**Comment by acao** [comment]
my bad, let this one pass through, I'm on it!
https://github.com/graphql/graphiql/blob/7c381f9d7dc73ec30ca09356c9ae2efb9f0de883/packages/graphiql/src/utility/commonKeys.js#L1

**Comment by Fi1osof** [comment]
Will wait updates. Thanks! 
Now use 0.13.2 yet.

**Comment by acao** [comment]
@Fi1osof - 0.14.1 released! SSR is my bread and butter so that was embarassing. good thing we caught it early, thanks!

**Comment by acao** [comment]
@Fi1osof you're right about my mistake.  that's embarassing, apologies 4:30am bugfix here, haha

**Comment by benjie** [comment]
@acao Did you mean to re-open this?

**Comment by Fi1osof** [comment]
@acao, thanks!
